### ISSUE TITLE
Feature Request: Release package signing

### ISSUE THREAD

**Issue by g4jc** [perlorg/perlweb#205]
Hello,
There is currently no way to verify the integrity of releases. Please consider signing your releases so that package maintainers can verify the sources prior to packaging.

See here for how-to and complete details:
https://wiki.debian.org/Creating%20signed%20GitHub%20releases

This affects the core of Perl, which is currently listed for download here:
http://www.cpan.org/src/5.0/

Thank you

**Comment by rspier** [comment]
All released perl source tarballs have three signatures:  md5, sha1, and sha256

If you are looking for git signatures, you should contact [perl5-porters](https://lists.perl.org/list/perl5-porters.html).  If your issue is with CPAN, you should contact [modules](https://lists.perl.org/list/modules.html).

**Comment by Tsutsukakushi** [comment]
@rspier Those are hashes. Hash can only be used to verify that a file didn't get corrupted during transmission, it's quite useless in case there is a malactor and you don't have another trusted way of transmitting the hash.

Also, I see no signatures of any kind at https://www.perl.org/get.html

**Comment by rspier** [comment]
This is the wrong place to report this issue.  See above.
